mkdir: cannot create directory '/tmp/lock-gpu0': File exists

Computing neighbors:   0%|          | 0/8 [00:00<?, ?it/s]
Computing neighbors:  12%|â–ˆâ–Ž        | 1/8 [02:45<19:15, 165.06s/it]
Computing neighbors:  25%|â–ˆâ–ˆâ–Œ       | 2/8 [05:25<16:12, 162.11s/it]
Computing neighbors:  38%|â–ˆâ–ˆâ–ˆâ–Š      | 3/8 [08:18<13:56, 167.27s/it]
Computing neighbors:  50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 4/8 [10:53<10:50, 162.54s/it]
Computing neighbors:  62%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Ž   | 5/8 [13:19<07:49, 156.52s/it]
Computing neighbors:  75%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ  | 6/8 [16:06<05:20, 160.03s/it]
Computing neighbors:  88%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Š | 7/8 [18:42<02:38, 158.76s/it]
Computing neighbors: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 8/8 [21:02<00:00, 152.90s/it]
Computing neighbors: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 8/8 [21:03<00:00, 157.88s/it]

Embeddings:   0%|[32m          [0m| 0/8 [00:00<?, ?it/s]

Metrics:   0%|[34m          [0m| 0/10 [00:00<?, ?it/s][A

Metrics:   0%|[34m          [0m| 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels][AWARNING:jax._src.xla_bridge:An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


Metrics:  10%|[34mâ–ˆ         [0m| 1/10 [3:37:25<32:36:47, 13045.23s/it, Bio conservation: isolated_labels][A

Metrics:  10%|[34mâ–ˆ         [0m| 1/10 [3:37:25<32:36:47, 13045.23s/it, Bio conservation: nmi_ari_cluster_labels_kmeans][A
Embeddings:   0%|[32m          [0m| 0/8 [3:37:25<?, ?it/s]
Traceback (most recent call last):
  File "/wynton/group/gartner/Qin/Concord_benchmark/jobs/Concord_CBCE/cbce_scib.py", line 68, in <module>
    bm.benchmark()
  File "/wynton/home/gartner/zhuqin/.conda/envs/cellpath/lib/python3.9/site-packages/scib_metrics/benchmark/_core.py", line 221, in benchmark
    metric_value = getattr(MetricAnnDataAPI, metric_name)(ad, metric_fn)
  File "/wynton/home/gartner/zhuqin/.conda/envs/cellpath/lib/python3.9/site-packages/scib_metrics/benchmark/_core.py", line 86, in <lambda>
    nmi_ari_cluster_labels_kmeans = lambda ad, fn: fn(ad.X, ad.obs[_LABELS])
  File "/wynton/home/gartner/zhuqin/.conda/envs/cellpath/lib/python3.9/site-packages/scib_metrics/_nmi_ari.py", line 65, in nmi_ari_cluster_labels_kmeans
    n_clusters = len(np.unique(labels))
  File "/wynton/home/gartner/zhuqin/.conda/envs/cellpath/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 274, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts,
  File "/wynton/home/gartner/zhuqin/.conda/envs/cellpath/lib/python3.9/site-packages/numpy/lib/arraysetops.py", line 336, in _unique1d
    ar.sort()
TypeError: '<' not supported between instances of 'float' and 'str'


                                                                                                                [Amkdir: cannot create directory '/tmp/lock-gpu0': File exists

Computing neighbors:   0%|          | 0/8 [00:00<?, ?it/s]
Computing neighbors:  12%|â–ˆâ–Ž        | 1/8 [03:30<24:35, 210.80s/it]
Computing neighbors:  25%|â–ˆâ–ˆâ–Œ       | 2/8 [07:12<21:43, 217.26s/it]
Computing neighbors:  38%|â–ˆâ–ˆâ–ˆâ–Š      | 3/8 [11:11<18:55, 227.03s/it]
Computing neighbors:  50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 4/8 [14:28<14:20, 215.13s/it]
Computing neighbors:  62%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Ž   | 5/8 [17:30<10:09, 203.30s/it]
Computing neighbors:  75%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ  | 6/8 [21:07<06:56, 208.06s/it]
Computing neighbors:  88%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Š | 7/8 [24:42<03:30, 210.24s/it]
Computing neighbors: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 8/8 [28:05<00:00, 207.80s/it]
Computing neighbors: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 8/8 [28:05<00:00, 210.63s/it]

Embeddings:   0%|[32m          [0m| 0/8 [00:00<?, ?it/s]

Metrics:   0%|[34m          [0m| 0/10 [00:00<?, ?it/s][A

Metrics:   0%|[34m          [0m| 0/10 [00:00<?, ?it/s, Bio conservation: isolated_labels][AWARNING:jax._src.xla_bridge:An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


Metrics:  10%|[34mâ–ˆ         [0m| 1/10 [5:50:30<52:34:35, 21030.58s/it, Bio conservation: isolated_labels][A

Metrics:  10%|[34mâ–ˆ         [0m| 1/10 [5:50:30<52:34:35, 21030.58s/it, Bio conservation: nmi_ari_cluster_labels_kmeans][A
Embeddings:   0%|[32m          [0m| 0/8 [5:50:35<?, ?it/s]
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/wynton/group/gartner/Qin/Concord_benchmark/jobs/Concord_CBCE/cbce_scib.py", line 71, in <module>
    bm.benchmark()
  File "/wynton/home/gartner/zhuqin/.conda/envs/cellpath/lib/python3.9/site-packages/scib_metrics/benchmark/_core.py", line 221, in benchmark
    metric_value = getattr(MetricAnnDataAPI, metric_name)(ad, metric_fn)
  File "/wynton/home/gartner/zhuqin/.conda/envs/cellpath/lib/python3.9/site-packages/scib_metrics/benchmark/_core.py", line 86, in <lambda>
    nmi_ari_cluster_labels_kmeans = lambda ad, fn: fn(ad.X, ad.obs[_LABELS])
  File "/wynton/home/gartner/zhuqin/.conda/envs/cellpath/lib/python3.9/site-packages/scib_metrics/_nmi_ari.py", line 66, in nmi_ari_cluster_labels_kmeans
    labels_pred = _compute_clustering_kmeans(X, n_clusters)
  File "/wynton/home/gartner/zhuqin/.conda/envs/cellpath/lib/python3.9/site-packages/scib_metrics/_nmi_ari.py", line 18, in _compute_clustering_kmeans
    kmeans.fit(X)
  File "/wynton/home/gartner/zhuqin/.conda/envs/cellpath/lib/python3.9/site-packages/scib_metrics/utils/_kmeans.py", line 131, in fit
    self._fit(X)
  File "/wynton/home/gartner/zhuqin/.conda/envs/cellpath/lib/python3.9/site-packages/scib_metrics/utils/_kmeans.py", line 137, in _fit
    all_centroids, all_inertias = jax.lax.map(
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory allocating 304983706240 bytes.


                                                                                                                [A